### PR TITLE
Use existing container definition

### LINKED ISSUE #43: Remote task fetching
Heya, is it possible to not have to include tasks in your source code and instead fetch them remotely? I have one that's defined in ECS and would like to use it

### PR DESCRIPTION
**Pull request by toote**
* Made the `container_definition` parameter optional (closes #43)
* Refactored the readme (into mandatory and optional parameters)
* refactored the code a bit to make it more streamlined
* cleaned-up the tests a bit
* bumped version in example to next release

### CODE REVIEW

**Comment by butterkitty** [comment]
Looks like it's not working quite right. It's creating a new revision of the task, but it's very stripped out.


Pipeline:
```yaml
steps:
  - label: ":ecs: :rocket:"
    concurrency_group: "my-service-deploy"
    concurrency: 1
    plugins:
      - ecs-deploy#c55fb7f04ef92f078c9f055b1eb0a690f236e934:
          cluster: "michelle-test-ecs"
          service: "michelle-test-service"
          task-family: "michelle-test-task"
          image: "alpine"  
```

**Everything AWS is made with the sandbox admin account**

Revision before running pipeline:
https://us-east-1.console.aws.amazon.com/ecs/v2/task-definitions/michelle-test-task/34/json?region=us-east-1
```json
{
    "taskDefinitionArn": "arn:aws:ecs:us-east-1:253213882263:task-definition/michelle-test-task:34",
    "containerDefinitions": [
        {
            "name": "amazon-ecs-sample",
            "image": "amazon/amazon-ecs-sample",
            "cpu": 1024,
            "memory": 2048,
            "portMappings": [
                {
                    "name": "amazon-ecs-sample-80-tcp",
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp",
                    "appProtocol": "http"
                }
            ],
            "essential": true,
            "environment": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/michelle-test-task",
                    "awslogs-region": "us-east-1",
                    "awslogs-stream-prefix": "ecs"
                }
            }
        }
    ],
    "family": "michelle-test-task",
    "executionRoleArn": "arn:aws:iam::253213882263:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 34,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "1024",
    "memory": "3072",
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "registeredAt": "2023-06-22T20:50:00.492Z",
    "registeredBy": "arn:aws:sts::253213882263:assumed-role/admin/michelle.p",
    "tags": []
}
```
Revision after running pipeline:
https://us-east-1.console.aws.amazon.com/ecs/v2/task-definitions/michelle-test-task/35/json?region=us-east-1
```json
{
    "taskDefinitionArn": "arn:aws:ecs:us-east-1:253213882263:task-definition/michelle-test-task:35",
    "containerDefinitions": [
        {
            "name": "amazon-ecs-sample",
            "image": "alpine",
            "cpu": 1024,
            "memory": 2048,
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "environment": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/michelle-test-task",
                    "awslogs-region": "us-east-1",
                    "awslogs-stream-prefix": "ecs"
                }
            }
        }
    ],
    "family": "michelle-test-task",
    "revision": 35,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EXTERNAL",
        "EC2"
    ],
    "registeredAt": "2023-06-22T20:50:19.770Z",
    "registeredBy": "arn:aws:sts::253213882263:assumed-role/MichelleP-buildkite-Role/i-0ea00006161c440e1",
    "tags": []
}
```

**Comment by butterkitty** [comment]
It looks like it will always create a new task definition revision without querying for what the old one included?

There is new logic in place for the container definition to allow it to be blank, but since it's creating a new task definition without the old information for the task itself, it's missing important parameters like the `app environment` and `network mode`.

I'm curious why we're creating a new task definition in this case, since you could just run the task/create a service for the task definition straight up right?

**Comment by toote** [comment]
> It looks like it will always create a new task definition revision without querying everything the old one included?

Nope, a new task definition will be created because that is the way ECS works 🤷 

> There is new logic in place for the container definition to allow it to be blank and query the defined definition, but since it's creating a new task definition without the old information for the task itself, the task definition is missing important parameters like the `app environment` and `network mode` still.

This PR is exactly for doing that. Here is where the existing task definition is queried: https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/pull/95/files#diff-94a101319341e0a2056fd83b6ec5656a8464b1af49f7192644132851e1256de6R29

Would you be able to check exactly what is returned there and if there are any additional parameters that need to be added to that call to get that information?

> I'm curious why we're creating a new task definition in this case, since you could just run the task/create a service for the task definition straight up right?

The only way to create the task is to know what is the _shape_ of the application, that is why this plugin required you to have the coomplete task definition as a file in the repo (which is what we are trying to change 😛)

**Comment by butterkitty** [comment]
Very interesting. Thanks for the info. My experience with the ECS Api really isn't the best, so I'm learning as I go right now.

I took a look at the output for the command being used that you pointed out and it is getting the container definition properly:
```
[
    {
        "name": "amazon-ecs-sample",
        "image": "amazon/amazon-ecs-sample",
        "cpu": 1024,
        "memory": 2048,
        "portMappings": [
            {
                "containerPort": 80,
                "hostPort": 80,
                "protocol": "tcp",
                "name": "amazon-ecs-sample-80-tcp",
                "appProtocol": "http"
            }
        ],
        "essential": true,
        "environment": [],
        "mountPoints": [],
        "volumesFrom": [],
        "logConfiguration": {
            "logDriver": "awslogs",
            "options": {
                "awslogs-create-group": "true",
                "awslogs-group": "/ecs/michelle-test-task",
                "awslogs-region": "us-east-1",
                "awslogs-stream-prefix": "ecs"
            }
        }
    }
]

```

If I change the command to `aws ecs describe-task-definition --task-definition "${task_family}" --query 'taskDefinition' ` I can see the entire taskDefinition instead of just the containerDefinition.
```
{
    "taskDefinitionArn": "arn:aws:ecs:us-east-1:253213882263:task-definition/michelle-test-task:37",
    "containerDefinitions": [
        {
            "name": "amazon-ecs-sample",
            "image": "amazon/amazon-ecs-sample",
            "cpu": 1024,
            "memory": 2048,
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp",
                    "name": "amazon-ecs-sample-80-tcp",
                    "appProtocol": "http"
                }
            ],
            "essential": true,
            "environment": [],
            "mountPoints": [],
            "volumesFrom": [],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-create-group": "true",
                    "awslogs-group": "/ecs/michelle-test-task",
                    "awslogs-region": "us-east-1",
                    "awslogs-stream-prefix": "ecs"
                }
            }
        }
    ],
    "family": "michelle-test-task",
    "executionRoleArn": "arn:aws:iam::253213882263:role/ecsTaskExecutionRole",
    "networkMode": "awsvpc",
    "revision": 37,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
        {
            "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
        },
        {
            "name": "ecs.capability.execution-role-awslogs"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
        },
        {
            "name": "ecs.capability.task-eni"
        },
        {
            "name": "com.amazonaws.ecs.capability.docker-remote-api.1.29"
        }
    ],
    "placementConstraints": [],
    "compatibilities": [
        "EC2",
        "FARGATE"
    ],
    "runtimePlatform": {
        "cpuArchitecture": "X86_64",
        "operatingSystemFamily": "LINUX"
    },
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "1024",
    "memory": "3072",
    "registeredAt": "2023-06-23T11:43:10.141000-04:00",
    "registeredBy": "arn:aws:sts::253213882263:assumed-role/admin/michelle.p"
}
```

I don't have the best experience with the ECS API, but is it possible to have pull this here and use this to create the new version of the task definition, just like if you defined it in the source code?

If we do this section by section, we'd have to include all below. Looking at [this](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Types.html) page, I'm not sure how you would access some of these without querying the taskDefinition directly like I did in the above command. That taskDefinition would then include the containerDefinition(s) as well:
* executionRoleArn
* networkMode
* volumes
* requiresAttributes
* placementConstraints
* compatibilities
* runtimePlatform
* requiresCompatibilities
* cpu (the task itself's cpu requirements)
* memory (the task itself's memory requirements)

**Comment by toote** [comment]
That is a great piece of research and exactly the information necessary. Obviously, re-using the task definition requires a lot more work, specially around https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/pull/95/files#diff-94a101319341e0a2056fd83b6ec5656a8464b1af49f7192644132851e1256de6L146-L151

**Comment by butterkitty** [comment]
> That is a great piece of research and exactly the information necessary. Obviously, re-using the task definition requires a lot more work, specially around https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/pull/95/files#diff-94a101319341e0a2056fd83b6ec5656a8464b1af49f7192644132851e1256de6L146-L151

Thank you very much. I put some work in trying to make sure it had as much information as I could find.

Agreed. This is going to take some amount of work, and that spot is where it should be done. I can see what I can put together for this, or you can, but this is more than just a simple fix.

**Comment by butterkitty** [comment]
Hey @toote !

I'm trying to get this tested, and it looks like it's working a lot better, since it's actually keeping my settings!

But I want to do a good test of it, and am stuck on a part of it.

It seems that I have to configure the network when creating the service based on the task definition. As far as I can tell this should be done by the plugin? 

The exact error I'm getting:
```
An error occurred (InvalidParameterException) when calling the CreateService operation: Network Configuration must be provided when networkMode 'awsvpc' is specified.
```

**Comment by toote** [comment]
@butterkitty great to know that it is working when updating the service!

The scenario you are mentioning appears to be something to do with creating services with `awsvpc` networking mode defined in them, in which case the call to the CreateService AWS API requires additional parameters (`--network-configuration`) that, from what I can read, is not supported with the current code either so it may be out of scope for this (already way oversized) PR. That said, it means that the plugin can not create Fargate services (as they require awsvpc networking mode).

**Comment by butterkitty** [comment]
@toote that makes a lot of sense.

I've tested it using an EC2 cluster and the wordpress image and it seems to work perfectly.

I'm not sure it it was in scope of this PR, but it can't seem to be able to use existing services. I don't think it is, but I figured I'd mention it just in case!

Let me know! 💖

**Review by pzeballos — APPROVED** [review]
Based on @butterkitty extended review 🎉, this PR looks good to merge :)  We can add a clarification that we don't support Fargate, so you'll need to have the service already created (only update)

**Comment by toote** [comment]
> I'm not sure it it was in scope of this PR, but it can't seem to be able to use existing services. I don't think it is, but I figured I'd mention it just in case!

@butterkitty I really hope you meant it the other way around: that it worked for existing services but did not for creating new services (with `awsvpc` networking mode), right?

**Comment by elijahchancey** [comment]
Will this PR be able to bump the image tag within an existing ECS Fargate service?

**Comment by elijahchancey** [comment]
Also, when is this getting merged? kthxbai

**Comment by elijahchancey** [comment]
When I attempt to use this PR's version of the Plugin, I see this error:
image
"Cannot update a service to add/remove a load balancer. First delete the service and then run again, or rename the service to force a new one to be created. Container config differs"

This is how I use the plugin in pipeline.yml:
```
- label: "Deploy"
    depends_on: ["build"]
    plugins:
      - ecs-deploy#toote_use_existing_container_definition:
          cluster: "primary"
          service: "api"
          task-family: "api"
          image: "4242424242.dkr.ecr.eu-central-1.amazonaws.com/api:bk-$BUILDKITE_BUILD_NUMBER"
```

I verified that the plugin was able to create a new task revision, and the correct image/build is specified. The task.json is attached.

Thanks for your help!
[task-def.json](https://github.com/buildkite-plugins/ecs-deploy-buildkite-plugin/files/13301426/task-def.json)

**Comment by elijahchancey** [comment]
Also, here's a screenshot of a diff of the task definition revisions. 
198 = new revision created by this plugin
197 = old revision that was created by https://github.com/aws-actions/amazon-ecs-deploy-task-definition

PS, I'm currently trying to migrate from github actions to buildkite
PPS thanks again!

**Comment by toote** [comment]
@elijahchancey thanks a lot for all that information! It looks as if the task definition is setup correctly which is a huge relief. The issue you are facing appears to be with the load balancer or target group, which makes sense as your pipeline does not have one defined but apparently your service does. We'll be more than happy to look further into it but I believe that it should be a separate issue/PR for that so that we can troubleshoot it separately.

**Comment by pzeballos** [comment]
We'll merge this one, but we are not going to do a release yet. We'll work on #100 and do a major release

**Pull request merged**
