### PR TITLE
Support Classic Load Balancers

### PR DESCRIPTION
**Pull request by patrobinson**

### CODE REVIEW

**Comment by toolmantim** [comment]
Is it feasible to look at removing the create service functionality from this plugin altogether, and perhaps moving it into an envato one? Because I think @lox and I were keen to pair this down to only deployment. And it means you can also have a simpler IAM role recommendation for just this plugin use too.

It should simplify things for this plugin so we can more actively use and maintain it ourselves, as it seems a lot of complexity lies in the service setup?

**Comment by patrobinson** [comment]
Hey @toolmantim I've been meaning to update the README with a limited number of IAM privileges required. Here's a basic policy we are using:

```
Policy:
  Statement:
  - Action:
    - cloudformation:DescribeStacks
    - ecr:DescribeImages
    - ecs:CreateService
    - ecs:DescribeServices
    - ecs:RegisterTaskDefinition
    - ecs:UpdateService
    Effect: Allow
    Resource: '*'
  - Action: iam:Passrole
    Effect: Allow
    Resource:
    - arn:aws:iam::012345678910:role/service-A-task-role
    - arn:aws:iam::012345678910:role/service-B-task-role
  Version: 2012-10-17
```

The reason I chose to create the service in the plugin is:
- The service is tightly coupled to the task, you cannot create a service without a task definition. This requires some bootstrapping then before you can use the plugin. IMO it's a better use experience for this plugin if they can just import and start using it without extra steps, which we'd have to document for them.
- If a service is deleted somehow, say you delete a cluster or migrate tasks to a different cluster, we'll handle that automatically.
- Load Balancers are defined at the service level, instead of forcing the user to create the service manually with some dummy task and the load balancer configuration, we can do that heavy lifting for them.

**Comment by toolmantim** [comment]
Thanks for the context. I think for many first users they might just be wanting to hook up deployment of something that’s already set up. For example, for us, the service and ALB is managed via Terraform (and we don’t always have a load balancer for a service).

But I don’t really mind keeping support for creation, so long as we can document just the deployment separately to the feature of “it can also create and update the service definition itself”.

We’ll need to be clearer on what options are required for the two different use cases, and also the different IAM for the two different use cases.

I’m keen to remove the “Alpha” label off this and tag v1.0.0 though. I’ll look at moving our site onto this, now I know the target stuff is optional, and updating the readme.

**Comment by patrobinson** [comment]
This will work once #33 is merged and we rebase against it

**Pull request merged**
